### ISSUE TITLE
Suggestion about removing unnecessary 'using'  

### ISSUE THREAD

**Issue by Mooophy** [scottszb1987/LeetCodeInCSharp#1]
``` csharp
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
```

Generated by VS, such statements can be found in almost every file in this repo. Just suggest to remove these `using NeverUsedNameSpace`. I think this should be a good practice.

**Comment by bysz71** [comment]
Hmmm, that make sense. But why are they there? Which ones are compulsory? I think I will post a question on stackoverflow.

**Comment by Mooophy** [comment]
Can you paste the link to the question you post on SO?

**Comment by Mooophy** [comment]
I went through a few similar questions on SO including yours. Most are from performance or other similar point of view. But my suggestion are based on something else, which are
- Giving reviewers an impression that the author (i.e. you) know which namespaces are being used and that everything is under control. Please think about who are going to read these codes.
- A start point to get familiar with the whole .Net namespace system architecture. Without this knowledge, it's gonna be quite hard to delete those unnecessary `using`.

**Comment by bysz71** [comment]
For the first thing you mention, yes, I've always had that in mind, I will put links into every questions later.

For the `using` problem, here is the [[stackoverflow link]](https://stackoverflow.com/questions/32730027/is-it-good-practice-to-remove-un-used-namespaces-in-c-sharp-class-files-which-ar)
According to the answers, the un-used `using` does not affect execution efficiency, and barely affect the compilation efficiency. I'm thinking I might keep them there, since some of them were truly used and some of them are potentially, and because it is not too many lines there, codes are still neat with them.

**Comment by Mooophy** [comment]
All good.

**Comment by kevinzhang2012** [comment]
Haha
